import './components/page.js'
import './components/template.js'
import './components/aside.js'
import './components/main.js'
import './components/welcome.js'
import './components/chat.js'
import './components/examples.js'
import './components/history.js'
import './components/prompt-input.js'
import './components/assistants.js'
import './components/user.js'
import './components/image-viewer.js'

